app_secrets:
    scm_trilogy_git_private_key:  |
        -----BEGIN RSA PRIVATE KEY-----
        row1
        row2
        row3
        -----END RSA PRIVATE KEY-----
test_combination: alt_env_full_name-${alt_env_full_name}-alt_env_name-${alt_env_name}
alt_env_name: dev
